// pages/_app.js
import { CartProvider } from 'react-use-cart';
import '../app/globals.css'; // Adjust the path based on your project structure
import Header from '@/components/header';
import Footer from "@/components/Footer";
import { Geist, Geist_Mono } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function MyApp({ Component, pageProps }) {


  return( <>
  <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
  <CartProvider id='products'>
  <Header/>
  <Component {...pageProps} />
  </CartProvider>
  <Footer/>

</div></>)
}

export default MyApp;